### ISSUE TITLE
How to send mail with attachment using nodeJs

### ISSUE THREAD

**Issue by Dev-Aman7** [sendgrid/sendgrid-nodejs#1001]
I am following this example 
```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello attachment',
  html: '<p>Here’s an attachment for you!</p>',
  attachments: [
    {
      content: 'Some base 64 encoded attachment content',
      filename: 'some-attachment.txt',
      type: 'plain/text',
      disposition: 'attachment',
      contentId: 'mytext'
    },
  ],
};
```

and this is my code
```
const SGmail = require('@sendgrid/mail');
const fs=require('fs');
const ejs=require('ejs');
require('dotenv').config();

SGmail.setApiKey(process.env.Key); // Input Api key or add to environment config

function newUserEmail(email){

  ejs.renderFile(__dirname+"\\views\\test.ejs",{name: 'Aman' },function(err,data){
      if(err)
      {
          console.log(err);
      }
      const msg = {
        to: email,
        from: '*******',
        subject: 'Testing',
        text: 'and easy to do anywhere, even with Node.js',
        html: data,
        attachments: [
            {
              content: 'Some base 64 encoded attachment content',
              filename:'het.txt',
              type: 'plain/text',
              disposition: 'attachment',
              contentId: 'mytext'
            },
          ]
        
      };
      SGmail.send(msg,function(err,data){
          if(err)
          console.log(err);
          else
          console.log('all good');
      });
      console.log("sent");

  });
     
    };
    
module.exports = {
    newUserEmail
};
```

I am getting error as Bad request
```
Error: Bad Request
    at Request.http [as _callback] (H:\Projects\SendGridMail\node_modules\@sendgrid\client\src\classes\client.js:124:25)    at Request.self.callback (H:\Projects\SendGridMail\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (H:\Projects\SendGridMail\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (H:\Projects\SendGridMail\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 400,
  message: 'Bad Request',
  response:
   { headers:
      { server: 'nginx',
        date: 'Wed, 13 Nov 2019 22:31:07 GMT',
        'content-type': 'application/json',
        'content-length': '209',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } }
{ Error: Bad Request
    at Request.http [as _callback] (H:\Projects\SendGridMail\node_modules\@sendgrid\client\src\classes\client.js:124:25)    at Request.self.callback (H:\Projects\SendGridMail\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (H:\Projects\SendGridMail\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (H:\Projects\SendGridMail\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 400,
  message: 'Bad Request',
  response:
   { headers:
      { server: 'nginx',
        date: 'Wed, 13 Nov 2019 22:31:08 GMT',
        'content-type': 'application/json',
        'content-length': '209',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } }
PS H:\Projects\SendGridMail> node app
Server running on 3000
sent
sent
{ Error: Bad Request
    at Request.http [as _callback] (H:\Projects\SendGridMail\node_modules\@sendgrid\client\src\classes\client.js:124:25)
    at Request.self.callback (H:\Projects\SendGridMail\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (H:\Projects\SendGridMail\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (H:\Projects\SendGridMail\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 400,
  message: 'Bad Request',
  response:
   { headers:
      { server: 'nginx',
        date: 'Wed, 13 Nov 2019 22:32:40 GMT',
        'content-type': 'application/json',
        'content-length': '209',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } }
```
#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by childish-sambino** [comment]
Recommend logging the error response body for details about why the request was rejected:
```
if (err)
    console.error(err.response.body);
```
