### ISSUE TITLE
tunneling socket could not be established

### ISSUE THREAD

**Issue by jay-dev23** [sendgrid/sendgrid-nodejs#1033]
### Issue Summary
Have been cracking my head around this error for days and couldn't help myself..
Tunneling socket could not be established, 

### Code Snippet
```node
router.post('/forgot',(req,res)=>    
    {
      let email = req.body.forgot;
      console.log(email)
      SGmail.setApiKey(process.env.SECRET_API);
      const msg = {
        to: email,
        from: '<test@test.com>',
        subject: 'Sending with Twilio SendGrid is Fun',
        text: 'and easy to do anywhere, even with Node.js',
        html: '<strong>and easy to do anywhere, even with Node.js</strong>',
      };
      SGmail.send(msg,true,function cb(err,result){
        if(err){
          console.error(err);
        }
        console.log(result)

      })

```
### Error
```node
{ Error: tunneling socket could not be established, statusCode=302
    at ClientRequest.onConnect (D:\javaSCript\Doctree\main\node_modules\tunnel-agent\index.js:166:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnData (_http_client.js:475:11)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) code: 'ECONNRESET' }
}
```
### Technical details:
* sendgrid-nodejs version:@sendgrid/mail: "^6.4.0"
* node version:v10.16.3

**Comment by childish-sambino** [comment]
Sounds like an issue with a proxy. Were you able to resolve this and/or reconfigure the proxy?
