### ISSUE TITLE
An authorization error occurs on sendgrid

### ISSUE THREAD

**Issue by cjstk7168** [sendgrid/sendgrid-nodejs#1046]
### Issue Summary
First, Sorry... I'm not good English.

I use CI from Jest.
When execute jest test code, It sometime not working.
An authorization error occurs on sendgrid.

But I'm not import sendgrid in test code.

Do you know why?

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```
    Unauthorized

      at Request._callback (../node_modules/@sendgrid/client/src/classes/client.js:124:25)
      at Request.self.callback (../node_modules/request/request.js:185:22)
      at Request.<anonymous> (../node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (../node_modules/request/request.js:1083:12)

### Technical details:
* sendgrid-nodejs version: 6.4.0
* node version:
12.x

**Comment by childish-sambino** [comment]
Difficult to debug without knowing more about your setup. Maybe you're running the SendGrid tests instead of your own app's? Or your test is invoking something in your code that's invoking the SG client and trying to make an API call?
