### ISSUE TITLE
Missing destination email

### ISSUE THREAD

**Issue by shikunli-qq** [sendgrid/sendgrid-nodejs#1047]
### Issue Summary
I updated my app for just a few lines for an authentication service (user log into my app), which doesn't touch the code relevant to using sendgird. However, sendgird issues an error ever since that change:
```
Missing destination email
```
Is it possible that sendgrid has some dependency about anything?

### Code Snippet
```javascript
var email = {
	from:"name here <email_address>",
	to: "",
	// bcc: "",
	subject: "title here",
	html:  `text_here`,
	attachments:[
		{
			filename : 'checklist.pdf',
			path: './test.pdf'
		}
	]
};
email.to = $scope.input.email.toLowerCase();
configureSteps.sendEmail(email,configureOutcomes.stepList);
```

```
configureSteps.sendEmail = function(email, fileList){
	$http.post('/sendEmail', [email,fileList]);
}
```

### Exception/Log
```
[28/02/2020 16:08:42.903] [LOG]    Error: Missing destination email
    at Request._callback (C:\Project\HCA\ADFz-host-config-guide\node_modules\nod
emailer-sendgrid-transport\node_modules\sendgrid\lib\sendgrid.js:88:25)
    at Request.self.callback (C:\Project\HCA\ADFz-host-config-guide\node_modules
\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\Project\HCA\ADFz-host-config-guide\node_modules\r
equest\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (C:\Project\HCA\ADFz-host-config-guide\node_m
odules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) 
```

### Technical details:
* sendgrid-nodejs version:
        "nodemailer": "^2.7.0",
        "nodemailer-sendgrid-transport": "^0.2.0",
* node version:
        "node": "8.16.0"

**Comment by childish-sambino** [comment]
[nodemailer-sendgrid-transport](https://github.com/sendgrid/nodemailer-sendgrid-transport) is no. longer supported so I can't speak to any errors you're getting when using it.
