### ISSUE TITLE
How to fix bad request when migrating from nodemailer to sendgrid

### ISSUE THREAD

**Issue by shikunli-qq** [sendgrid/sendgrid-nodejs#1048]
### Issue Summary
nodemailer used to work for me but ran into problem recently after I updated the authentication part of my app - which should have no dependency on nodemailer...Anyway, since nodemailer is out of support, I begin to use sendgrid instead. I updated to `var sgMail = require('@sendgrid/mail')` and `sgMail.send()`.
However, after the code change, I encountered a "bad request" error and want to ask for help on how to fix it. 

### Steps to Reproduce
Only code snippets for view-controller-server are provided. The workflow is:
1) Take a couple of files and use `html-pdf` to convert those to a myfile.pdf
2) Call `sendgrid` to send an email with myfile.pdf attached

### Code Snippet
My `server.js`
```node
var pdf = require('html-pdf');
var path=require('path');

function generatePDF(fileList,emailInfo){
   // process _fileList_ to be myfile.pdf
   sendNotification(emailInfo);
}

var sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

function sendNotification(emailDetail){

    sgMail.send(emailDetail, function(err, info) {
        if (err) {
            console.log(err);
        } else {
            console.log(info, "send notification successfully");
        }
    });  
}

app.post('/sendEmail', function(req, res, next){
    generatePDF(req.body[1],req.body[0]);
    res.json({
        "status": "success"
    });
}); 
```

My `service.js`
```node
controller.sendEmail = function(email, fileList){
       $http.post('/sendEmail', [email,fileList]);
```

My `controller.js`
```node
var email = {
	from:"my_email",
	to: "user_email",
	subject: "title here",
	html:  `content here`,
	attachments:[
		{
			filename : 'myfile.pdf',
			path: './myfile.pdf'
		}
	]
};
controller.sendEmail(email,files);
```

### Exception/Log
```
[02/03/2020 14:29:23.880] [LOG]    ResponseError: Bad Request
    at Request._callback (C:\Project\HCA\ADFz-host-config-guide\node_modules\@se
ndgrid\client\src\classes\client.js:124:25)
    at Request.self.callback (C:\Project\HCA\ADFz-host-config-guide\node_modules
\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\Project\HCA\ADFz-host-config-guide\node_modules\r
equest\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (C:\Project\HCA\ADFz-host-config-guide\node_m
odules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 400,
  message: 'Bad Request',
  response: {
    headers: {
      server: 'nginx',
      date: 'Mon, 02 Mar 2020 06:29:22 GMT',
      'content-type': 'application/json',
      'content-length': '390',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of
, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.h
tml'
    },
    body: { errors: [Array] }
  }
}

```

### Technical details:
* sendgrid-nodejs version: "@sendgrid/mail": "^6.5.3"
* node version: "node": "8.16.0"

**Comment by childish-sambino** [comment]
Can you try logging the error response body to see what is causing the bad request?
```
console.error(err.response.body);
```

**Comment by shikunli-qq** [comment]
Thanks for the tip! Now things are clearer:
```
  errors: [
    {
      message: 'The attachment content is required.',
      field: 'attachments.0.content',
      help: 'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#
message.attachments.content'
    },
    {
      message: 'Does not contain a valid address.',
      field: 'personalizations.0.to.0.email',
      help: 'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#
message.personalizations.to'
    }
  ]
```
1. As I need to attach a PDF file, could you kindly suggest how I should fill in the attachements.0.content field?
2. I added the personalizations field as follows, but the error remains:
```node
personalizations: [
	{to: [
	{email: "aaa@bb.com"}
],
}],
from:"xxx <xxx@y.z.com>",
to: [
	{email: "aaa@bb.com"}
],
```
BTW, actually the email is inputted by my users on the UI, so it would be a variable instead of a string. Can I use it as `email: my_variable`?

**Comment by childish-sambino** [comment]
There's an example here for sending with an attachment: https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/attachments.md

Instead of passing a path to the file, you'll need to pass the content of the file base64-encoded.
