### ISSUE TITLE
403 Forbidden error sending simple email

### ISSUE THREAD

**Issue by aledap** [sendgrid/sendgrid-nodejs#1090]
Getting a 403 Forbidden error on sending a simple email via my Node project. Simply following the official integration guide. My API Key has full access. The code integration is correct as I have used an API Key from another account and it works perfectly. It is only with a particular account that this issue is present.

### Exception/Log
```
ResponseError: Forbidden
    at Request._callback (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 403,
  message: 'Forbidden',
  response: {
    headers: {
      server: 'nginx',
      date: 'Sat, 11 Apr 2020 08:16:23 GMT',
      'content-type': 'application/json',
      'content-length': '281',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
    },
    body: { errors: [Array] }
  }
}
```

* sendgrid-nodejs version: 6.5.5
* node version: 12.16.1

**Comment by GuySerfaty** [comment]
+1

**Comment by anuj-agrawal1997** [comment]
Me too

**Comment by eshanholtz** [comment]
Hi @aledap ,
I haven't been able to recreate this issue, but it looks like it's being investigated over in #957. I'm going to close this issue as a duplicate and I encourage you to follow up over there.

**Comment by prolok** [comment]
The other thread (#957 ) has been locked and thus I can only reply here.

I just create a new account, following the sample to create the simple send email function. When I run the code, I got the error 403.

My account is on free plan, the API key has been granted full access. What have I missed?

**Comment by childish-sambino** [comment]
@prolok Try logging the error response body to get more details about what's going on. Example here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/success-failure-errors.md

**Comment by prolok** [comment]
@childish-sambino it is exactly the same as what @aledap has quoted from the beginning, so any idea for such error response?

**Comment by childish-sambino** [comment]
The OP's log does not include the full response body which has additional details. E.g., `console.error(error.response.body)`

**Comment by aledap** [comment]
Hi @prolok , I solved it by performing 'Single Sender Authentication' on my Sendgrid account. 
However, I have another account and I have not verified any domain or sender email, but I am still able to send an email from that account from ANY email specified. Not sure what the real issue is.

**Comment by prolok** [comment]
@childish-sambino below is my pm2 log when calling the function I copied from the integration guide and the function is triggered by a simple GET method in express js.

```
0|app      | 2020-04-27T20:06:00: { Error: Forbidden
0|app      | 2020-04-27T20:06:00:     at axios.then.catch.error (C:\Users\AdminGCS\Documents\HA_Inspection\node_modules\@sendgrid\client\src\classes\client.js:105:29)
0|app      | 2020-04-27T20:06:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
0|app      | 2020-04-27T20:06:00:   code: 403,
0|app      | 2020-04-27T20:06:00:   message: 'Forbidden',
0|app      | 2020-04-27T20:06:00:   response:
0|app      | 2020-04-27T20:06:00:    { headers:
0|app      | 2020-04-27T20:06:00:       { server: 'nginx',
0|app      | 2020-04-27T20:06:00:         date: 'Mon, 27 Apr 2020 12:06:00 GMT',
0|app      | 2020-04-27T20:06:00:         'content-type': 'application/json',
0|app      | 2020-04-27T20:06:00:         'content-length': '281',
0|app      | 2020-04-27T20:06:00:         connection: 'close',
0|app      | 2020-04-27T20:06:00:         'access-control-allow-origin': 'https://sendgrid.api-docs.io',
0|app      | 2020-04-27T20:06:00:         'access-control-allow-methods': 'POST',
0|app      | 2020-04-27T20:06:00:         'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
0|app      | 2020-04-27T20:06:00:         'access-control-max-age': '600',
0|app      | 2020-04-27T20:06:00:         'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
0|app      | 2020-04-27T20:06:00:      body: { errors: [Array] } } }
```
how can I get the `error.response.body` you mentioned? I think the `error` is not getting from any part of my code (at least cannot captured from try catch), could you tell me how can I getting the error body while I am calling `sgMail.send`?

**Comment by childish-sambino** [comment]
There's an example here of calling `sgMail.send` and catching/logging the error response and body.

**Comment by prolok** [comment]
@aledap thanks for your advise, it works.

@childish-sambino thanks for your reply; seems that following the guide will definitely missed the setup for the sender part, could the doc add a few alert for that part? (ok, maybe just because I am fool...)

**Comment by childish-sambino** [comment]
@prolok I updated the quckstart here fairly recently with this additional logging during failure: https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail#quick-start-hello-email

**Comment by redhorsedev** [comment]
@childish-sambino I ran into this problem while trying to get through the sendgrid onboarding (https://app.sendgrid.com/guide/integrate/langs/nodejs). The problem for me was that I was using single sender verification to get started but the guide did not specify that the to field had to match the single sender address. 

I see your quickstart does mention to change the from field but it would have been helpful to have emphasized this more throughout the onboarding. (especially as the onboarding says single sender auth is best suited for testing) 

Maybe this is obvious to people with more domain knowledge about this but when I've used other stmp email services, the from field never had to match anything for the email to be delivered

**Comment by memahesh** [comment]
@childish-sambino Sending email from any mail was possible previously, right. Is it still possible? If not, why was it removed? Also, is it possible to send the sender verification mail through API?

**Comment by childish-sambino** [comment]
@memahesh Best to reach out to [support](https://support.sendgrid.com/hc/en-us) as this is not something specific to this library.

**Comment by JhotamsDeveloper** [comment]
Hello, I know that the passage is already closed but I have found the documentation, this error is generated more than anything for people who have registered on April 6, 2020 or after or who have a free account.

[Check here](https://sendgrid.com/docs/ui/sending-email/sender-verification/)

**Comment by ElishaKay** [comment]
Guys,
I've tried upgrading my account to a paid plan - didn't work.
I've also tried setting up Sender Authentication - couldn't even get through it, even though I've added the DNS Records, and waited 48 hours for the DNS to populate.
I'm done with this - bad error logging, and the Sender Authentication is bugged up.
You have too many competitors to not be obsessed about the Onboarding flow here.

![image](https://user-images.githubusercontent.com/16700452/91653480-fdffe500-eaa9-11ea-8765-a0cb6c3a3c02.png)

I've already set up the code for automated one-time emails, but due to these bugs, I can't add users to a contact list, or even as a general contact.
P.S. I also filed a bug a month ago via the Support System within the app, and didn't hear back.
Highly recommend somebody in your organization prioritizes looking into this & actually tests this. 
I know it's not 'cool' to test, and you want to 'add new features', but if you're seeing a drop-off in onboarding stats - I wouldn't be surprised if it was due to this error: '403 not authorized'

**Comment by sudeshsakhardandecbre** [comment]
I had the same issue. I resolved it by using the same "From" address for all instances of SendGrid in different modules of our application.

**Comment by danish45007** [comment]
You can verify the integration after creating the api-key that will solve the problem

**Comment by nguyentran6698** [comment]
This is my solution for anyone still looking for resolution:
- For any person who just created sendGrid account you have to verify your Single Sender Verification before using the API. Also, you have to use the same email account that you submit in the Single Sender Verification in order to sending email.

**Comment by vssaini** [comment]
Double-check if you are using the correct email address in "From". This can also give you a "Forbidden" status code.

**Comment by rtcface** [comment]
gracias por la ayuda

**Comment by skimonkey** [comment]
Having to use a verified email address in the "From" field is fine when you are sending out emails to users. However it breaks the flow of a simple contact form, whereby users fill in their email address and the email is sent to my email address/mailbox. In this case I want the users email address as the "From" address so that I can reply to them. This always worked before but yet another thing that has been broken since sendgrid got bought by twillio.. :-(
This is the third time Im having to rewrite stuff due to breaking changes with no communication
Time to change to a new service
