### ISSUE TITLE
Getting same error again and again. Please check, I have added code and error message in console.

### ISSUE THREAD

**Issue by sumit409** [sendgrid/sendgrid-nodejs#1160]
this is my code---

```javascript
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'pappukumarwa12389@gmail.com',
  from: 'pappukumarwa12389@gmail.com', // Use the email address or domain you verified above
  subject: 'Sending with Twilio SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
//ES6
sgMail
  .send(msg)
  .then(() => {}, error => {
    console.error(error);

    if (error.response) {
      console.error(error.response.body)
    }
  });
```
--------------------------------------------------------------------
This is the error message in console--
```bash
PS C:\Users\HP\Desktop\sengrid_mail> node app.js
API key does not start with "SG.".
ResponseError: Unauthorized
    at C:\Users\HP\Desktop\sengrid_mail\node_modules\@sendgrid\client\src\classes\client.js:133:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 401,
  response: {
    headers: {
      server: 'nginx',
      date: 'Sat, 11 Jul 2020 07:19:34 GMT',
      'content-type': 'application/json',
      'content-length': '116',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
    },
    body: { errors: [Array] }
  }
}
{
  errors: [
    {
      message: 'The provided authorization grant is invalid, expired, or revoked',
      field: null,
      help: null
    }
  ]
}
PS C:\Users\HP\Desktop\sengrid_mail>  
```

**Comment by thinkingserious** [comment]
Hello @sumit409,

It looks like `process.env.SENDGRID_API_KEY` does not contain the correct value. Please check [this documentation](https://github.com/sendgrid/sendgrid-csharp#setup-environment-variables-to-manage-your-api-key) for how to do so in a Windows environment.

Thanks!

With best regards,

Elmer
