### ISSUE TITLE
'@sendgrid/mail@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by sujeet-agrahari** [sendgrid/sendgrid-nodejs#1174]
```
$ npm i @sendgrid/mail
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sendgrid%2fmail - Not found
npm ERR! 404
npm ERR! 404  '@sendgrid/mail@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```
Also tried installing with different version tags, yet getting same error.

**Comment by vedovelli** [comment]
Also happening here!

**Comment by vedovelli** [comment]
```
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Couldn't find package "@sendgrid/client@^7.2.3" required by "@sendgrid/mail@7.2.3" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@sendgrid/helpers@^7.2.3" required by "@sendgrid/mail@7.2.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by thomassiew** [comment]
Same here. was wondering the same , even send support tickets already.

**Comment by thomassiew** [comment]
![image](https://user-images.githubusercontent.com/25383324/89523437-6b0abc80-d815-11ea-9952-3a6d23661c3c.png)

**Comment by manpreetssethi** [comment]
Same here;

<img width="599" alt="Screenshot 2020-08-06 at 13 08 19" src="https://user-images.githubusercontent.com/2006753/89525076-f2d8d280-d7e5-11ea-86eb-d0331133c161.png">

**Comment by manpreetssethi** [comment]
FWIW; Looks like there's an incident on the NPM side - https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by manpreetssethi** [comment]
It worked for me, looks like the incident was the issue afterall.
