### ISSUE TITLE
Disposition argument no longer optional

### ISSUE THREAD

**Issue by dlq84** [sendgrid/sendgrid-nodejs#1179]
# Issue Summary
In version 7.2.1 or later (I haven't pinpointed the commit that caused the change) the disposition field in attachments are no longer optional and are not defaulting to 'attachment'. Either the docs or the code should change to reflect the docs

I'm getting this error: `Expected the attachment's 'disposition' field to be a string`

### Steps to Reproduce
1. leave out disposition when sending an email

### Exception/Log
```
Error: Expected the attachment's `disposition` field to be a string
    at Mail.setAttachments (/usr/src/app/node_modules/@sendgrid/helpers/classes/mail.js:448:13)
    at Mail.fromData (/usr/src/app/node_modules/@sendgrid/helpers/classes/mail.js:82:10)
    at new Mail (/usr/src/app/node_modules/@sendgrid/helpers/classes/mail.js:46:12)
    at Function.create (/usr/src/app/node_modules/@sendgrid/helpers/classes/mail.js:670:12)
    at MailService.send (/usr/src/app/node_modules/@sendgrid/mail/src/classes/mail-service.js:188:25)
    at MergeMapSubscriber.project (/usr/src/app/src/services/send-mail.service.ts:73:46)
    at MergeMapSubscriber._tryNext (/usr/src/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:135:21)
    at MergeMapSubscriber._next (/usr/src/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
    at MergeMapSubscriber.Subscriber.next (/usr/src/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/usr/src/app/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/usr/src/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Object.complete (/usr/src/app/node_modules/rxjs/src/internal/observable/forkJoin.ts:194:26)
    at Object.wrappedComplete (/usr/src/app/node_modules/rxjs/src/internal/Subscriber.ts:248:54)
    at SafeSubscriber.__tryOrUnsub (/usr/src/app/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
    at SafeSubscriber.complete (/usr/src/app/node_modules/rxjs/src/internal/Subscriber.ts:251:16)
    at Subscriber._complete (/usr/src/app/node_modules/rxjs/src/internal/Subscriber.ts:148:22)

```

### Technical details:
* sendgrid-nodejs version: >7.2.1
* node version: v13.14.0

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by TheOptimisticFactory** [comment]
Same thing happening with email `attachments` optional `type` property
![image](https://user-images.githubusercontent.com/2607260/90148276-76189c00-dd83-11ea-8dcc-a7340cde1572.png)

```js

const attachments = [{
  content: rawQrCodeBase64,
  content_id: 'qrcode',
  filename: 'qrcode.png',
  type: 'image/png',  // Sending any email without this property now fails
}];
```

**Comment by joel-cavli** [comment]
Got the same issue 

`Expected the attachment's `disposition` field to be a string`,

even after passing ` type: 'application/pdf'`

**Comment by TheOptimisticFactory** [comment]
@joel-cavli I ended forcing the default values for both optional `disposition: 'attachment'` and `type` fields since this bug is still happening after a month

Source: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters
![image](https://user-images.githubusercontent.com/2607260/93222133-e9d90a80-f76e-11ea-85d1-46407a5b4466.png)

**Comment by TheOptimisticFactory** [comment]
It is either
- `1)` A `bug in their API endpoint` under the assumption **the documentation is correct**. These parameters used to be omittable for at least a year and a half
- `2)` A case of `deprecated documentation` under the assumption **the API response is correct**. It would be a somewhat breaking change that none of the changelogs highlight.

Either way, it would be nice to have a definitive answer on whether it is a bug or the now-desired behavior

**Comment by childish-sambino** [comment]
It's a bug in the type-checking. PR submitted to fix this.

**Comment by adamreisnz** [comment]
Probably good practice to just specify the disposition explicitly anyway, just in case.
(Still not fixed by the way, I just got this error in Sentry)
