### ISSUE TITLE
either 'ids' OR 'delete_all_contacts' should be supplied as query param

### ISSUE THREAD

**Issue by sergiodev19** [sendgrid/sendgrid-nodejs#1185]
### Issue Summary
I send request to delete contact by id, but it was failed.

### Code Snippet
```node
const client = require('@sendgrid/client');
client.setApiKey(process.env.SENDGRID_API_KEY);

let request = {
        method: 'DELETE',
        url: `/v3/marketing/contacts`,
        qs: {
          "ids": ["<contact id here>"]
        }
      };

client.request(request)
  .then(([response, body]) => {
      return body;
   })
  .catch(err => console.log(err))
```

### Exception/Log
```
{ Error: Bad Request
    at axios.then.catch.error (node_modules/@sendgrid/client/src/classes/client.js:133:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 400,
  message: 'Bad Request',
  response: 
   { headers: 
      { server: 'nginx',
        date: 'Wed, 19 Aug 2020 14:13:44 GMT',
        'content-type': 'application/json',
        'content-length': '123',
        connection: 'close',
        'x-amzn-requestid': '94232114-2de5-4511-82eb-956578b04f27',
        'access-control-allow-origin': '*',
        'access-control-allow-headers': 'AUTHORIZATION, Content-Type, On-behalf-of, x-sg-elas-acl, X-Recaptcha, X-Request-Source',
        'x-amz-apigw-id': 'RhT_xEO0PHcFYkQ=',
        'access-control-allow-methods': 'PUT,DELETE,OPTIONS',
        'access-control-expose-headers': 'Link, Location',
        'x-amzn-trace-id': 'Root=1-5f3d3397-216c6559d836748c79d966fc;Sampled=0',
        'x-envoy-upstream-service-time': '118',
        'referrer-policy': 'strict-origin-when-cross-origin',
        'x-content-type-options': 'nosniff',
        'x-ratelimit-limit': '200',
        'x-ratelimit-remaining': '199',
        'x-ratelimit-reset': '17' },
     body: 
      { message: 'either \'ids\' OR \'delete_all_contacts\' should be supplied as query param',
        parameter: 'ids/delete_all_contacts' } } }
```

### Technical details:
* @sendgrid/client version: 7.2.3
* node version: 8.11.4

**Comment by childish-sambino** [comment]
According to the API docs:
> "ids" must set to comma separated contact ids for selected bulk contact delete

Have you tried just a string instead of an array of strings?

```
        qs: {
          "ids": "<contact id here>"
        }
```

**Comment by sergiodev19** [comment]
> According to the API docs:
> 
> > "ids" must set to comma separated contact ids for selected bulk contact delete
> 
> Have you tried just a string instead of an array of strings?
> 
> ```
>         qs: {
>           "ids": "<contact id here>"
>         }
> ```

@childish-sambino Thank you very much, it works now.
