### ISSUE TITLE
Error: Error: Parse Error: Duplicate Content-Length & Network Error

### ISSUE THREAD

**Issue by pradipvadher** [sendgrid/sendgrid-nodejs#1223]
Hello, I'm getting an error when trying to send mail from my server.

below is my config,
`try {
    sgMail.setApiKey(
      "SG.***************************.******************************8"
    );
    if (attachment) {
      request(attachment, { encoding: null }, (err, res, body) => {
        if (err) {
          return err;
        }
        if (body) {
          const textBuffered = Buffer.from(body);
          const msg = {
            to,
            from: "subscription@**************.com",
            subject,
            html: "",
            attachments: [
              {
                content: textBuffered.toString("base64"),
                filename,
                type: "application/pdf",
                disposition: "attachment",
                contentId: "myattachment",
              },
            ],
          };
          (async () => {
            try {
              await sgMail.send(msg);
            } catch (error) {
              console.error(error);
              if (error.response) {
                console.error(error.response.body);
              }
            }
          })();
        }
      });
    }
    const msg = {
      to,
      from: "subscription@***************8.com", // Use the email address or domain you verified above
      subject,
      text,
      html: "",
    };
    sgMail.send(msg).then(
      () => {},
      (error) => {
        console.error(error);
        if (error.response) {
          console.error(error.response.body);
        }
      }
    );
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }`

Exception Log:
`Error: Error: Parse Error: Duplicate Content-Length
    at Object.dispatchError (path/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
    at EventEmitter.<anonymous> (path//node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
    at EventEmitter.emit (events.js:326:22)
    at Request.<anonymous> (path//node_modules/jsdom/lib/jsdom/living/xhr-utils.js:412:47)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (path/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketOnData (_http_client.js:482:9)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) undefined
Error: Network Error
    at createError (path/node_modules/axios/lib/core/createError.js:16:15)
    at XMLHttpRequest.handleError (path/node_modules/axios/lib/adapters/xhr.js:83:14)
    at XMLHttpRequest.<anonymous> (path/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at invokeEventListeners (path/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at XMLHttpRequestEventTargetImpl._dispatch (path/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at XMLHttpRequestEventTargetImpl.dispatchEvent (path/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at XMLHttpRequest.dispatchEvent (path/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at requestErrorSteps (path/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:132:7)
    at Object.dispatchError (path/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:62:3)
    at EventEmitter.<anonymous> (path/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
    at EventEmitter.emit (events.js:326:22)
    at Request.<anonymous> (path/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:412:47)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (path/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketOnData (_http_client.js:482:9) {
  config: {
    url: '/v3/mail/send',
    method: 'post',
    data: '{"from":{"email":"subscription@*********.com"},"subject":"Test Mail - ********","personalizations":[{"to":[{"email":"pradip@*************.com"}]}],"content":[{"value":"Pradip ******* TEXT Content","type":"text/plain"},{"value":"","type":"text/html"}]}',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'User-Agent': 'sendgrid/7.4.0;nodejs',
      Authorization: 'Bearer SG.********************.***********************'
    },
    baseURL: 'https://api.sendgrid.com/',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: xhrAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    validateStatus: [Function: validateStatus]
  },
  request: XMLHttpRequest {
    upload: XMLHttpRequestUpload { _ownerDocument: [Document] },
    _registeredHandlers: Set { 'readystatechange' },
    _eventHandlers: [Object: null prototype] {
      readystatechange: [Function: handleLoad]
    },
    [Symbol(flag)]: {
      synchronous: false,
      withCredentials: false,
      mimeType: null,
      auth: null,
      method: 'POST',
      responseType: '',
      requestHeaders: [Object],
      referrer: 'about:blank',
      uri: 'https://api.sendgrid.com/v3/mail/send',
      timeout: 0,
      body: undefined,
      formData: false,
      preflight: true,
      requestManager: [RequestManager],
      pool: undefined,
      agentOptions: undefined,
      strictSSL: undefined,
      proxy: undefined,
      cookieJar: [CookieJar],
      encoding: 'UTF-8',
      origin: 'null',
      userAgent: 'Mozilla/5.0 (linux) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0'
    },
    [Symbol(properties)]: {
      beforeSend: false,
      send: false,
      timeoutStart: 0,
      timeoutId: 0,
      timeoutFn: null,
      client: [EventEmitter],
      responseHeaders: {},
      filteredResponseHeaders: [],
      responseBuffer: null,
      responseCache: null,
      responseTextCache: null,
      responseXMLCache: null,
      responseURL: '',
      readyState: 4,
      status: 0,
      statusText: '',
      error: [Error],
      uploadComplete: true,
      uploadListener: false,
      abortError: false,
      cookieJar: [CookieJar],
      bufferStepSize: 1048576,
      totalReceivedChunkSize: 0,
      requestBuffer: null,
      requestCache: null,
      origin: 'null'
    }
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}`

### Technical details:
* sendgrid-nodejs version: v7.4.0
* node version: v12.19.1

**Comment by MariuszKogut** [comment]
Make sure you are you are using ``testEnvironment: 'node'`` when running in jest.

**Comment by pradipvadher** [comment]
where I have to write `testEnvironment: 'node'`? in which file?

**Comment by MariuszKogut** [comment]
You could use ``jest.config.js`` in the root of your project. This is my configuration:

```
module.exports = {
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testPathIgnorePatterns: ['.*integration.test.ts'],
};
```

**Comment by pradipvadher** [comment]
Network Error disappear but `Error: Parse Error: Duplicate Content-Length` still there!

**Comment by pradipvadher** [comment]
`Error: Error: Parse Error: Duplicate Content-Length
    at Object.dispatchError (path/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
    at EventEmitter.<anonymous> (path/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
    at EventEmitter.emit (events.js:326:22)
    at Request.<anonymous> (path/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:412:47)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (path/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketOnData (_http_client.js:482:9)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by MariuszKogut** [comment]
I see in your stack trace you are still using ``jsdom`` as env and not ``node``. Check out jest documentation how to set the right environment. ==> https://jestjs.io/docs/en/configuration#testenvironment-string

**Comment by thinkingserious** [comment]
Hello @pradipvadher,

Thank for reporting this issue! Please let us know how it goes after reviewing @MariuszKogut's latest suggestion.

@MariuszKogut,

Thank you for taking a moment to help out, we appreciate it!

With best regards,

Elmer

**Comment by glenne** [comment]
Just add this to your jest test file:
`
/**
 * @jest-environment node
 */
`
