### ISSUE TITLE
HTTP 406 error code on mail send

### ISSUE THREAD

**Issue by wojteklu** [sendgrid/sendgrid-nodejs#1331]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

Randomly we receive exception on sending email:
```
message: "Not Acceptable"
stack: "Error: Not Acceptable
    at node_modules/@sendgrid/client/src/classes/client.js:146:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

### Steps to Reproduce

Code to reproduce:
```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(sendgridApiKey);
sgMail.send(data);
```

No way to reproduce as it happens randomly. I confirmed that data is not really important here. I could send mail with same data that was previously failing.

### Code Snippet
```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(sendgridApiKey);
sgMail.send(data);
```

### Exception/Log
```
message: "Not Acceptable"
stack: "Error: Not Acceptable
    at node_modules/@sendgrid/client/src/classes/client.js:146:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

### Technical details:
* sendgrid-nodejs version: "@sendgrid/mail": "^7.6.0"
* node version: 12.19.1

**Comment by brianschwabauer** [comment]
We're also seeing this error.

I don't think it's an issue with this library, but with the actual SendGrid API. We're been using version 6.5.3 of this library for more than a year now with no problems.

We haven't changed anything on our end in a long time. This error just started popping up in the last week.

**Comment by Sof31t** [comment]
@childish-sambino @thinkingserious @twilio-dx @eshanholtz can you help with this? Thanks you

**Comment by brianschwabauer** [comment]
Update - We haven't seen this error since Feb 14 @ 7:22pm CST. Prior to that, we were getting the error ~10 times a day. So it might be fixed? Or maybe just minimized?

**Comment by JenniferMah** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
