### ISSUE TITLE
SendGrid & Node.js - retrieving lists returns unauthorized

### ISSUE THREAD

**Issue by TomBell95** [sendgrid/sendgrid-nodejs#1350]
### Issue Summary
After following the sendgrid [documentation](https://docs.sendgrid.com/api-reference/contacts-api-lists/retrieve-all-lists) to retrieve all lists, keep getting the below **error**:

` ERROR  Unauthorized
  at node_modules/@sendgrid/client/src/classes/client.js:146:29
  at processTicksAndRejections (internal/process/task_queues.js:95:5)`

My API keys and sendgrid account have been set up **correctly**. This is confirmed by my contact form email working perfectly? So why would I receive an Unauthorized error?

### api/controller/contactController.js
```node
const client = require('@sendgrid/client');
const sgMail = require('@sendgrid/mail')

sgMail.setApiKey(process.env.SENDGRID_API_KEY)
client.setApiKey(process.env.SENDGRID_API_KEY)

// POST contact form - http://localhost:3000/contact-form
module.exports.contact = async function(req, res) {
    console.log('__________ contact form __________')
    console.log(req.body)
    try {
        const msg = {
            to: '<< MY EMAIL >>',
            from: {
                email: '<< MY AUTHENTICATED EMAIL >>', // Change to your verified sender
                name: '<< MY AUTHENTICATED EMAIL >> - New contact form enquiry',
            },
            subject: 'Contact form submission from << MY AUTHENTICATED EMAIL >>',
            text: 'New contact form submission',
            html: `<h3>Contact form submission from << MY AUTHENTICATED EMAIL >></h3>
                    <p>From: ${req.body.message.email}</p>
                    <p>Name: ${req.body.message.name}</p>               
                                
                    <p>Message: ${req.body.message.message}</p><br>               
                    <p>Please reply to the message separately, do not reply direct to this email!</p> `,
        }
        
        await sgMail
            .send(msg)
            .then(() => {
                console.log('Email sent')
                return res.json({ message: 'Email sent', status: true })
            })
            .catch((error) => {
                console.error(error)
                return res.json({ message: 'Error', status: false, error })
            })
        
    } catch (err) {
        console.log(err)
        return res.status(500).json({ message: 'Error contact form.'})
    }
}

// POST welcome email - http://localhost:3000/api/welcome-email
module.exports.welcome = function(req, res) {
    console.log('__________ welcome email __________')
    try {

        const headers = {
            "Authorization":`Bearer ${process.env.SENDGRID_API_KEY}`,
            "on-behalf-of": "The subuser's username. This header generates the API call as if the subuser account was making the call."
        };

        const request = {
        url: `/v3/contactdb/lists`,
        method: 'GET',
        headers
        }

        console.log(request)
        console.log(client)
        client.request(request)
        .then(([response, body]) => {
            console.log(response.statusCode);
            console.log(response.body);
        })
        .catch(error => {
            console.error(error);
        });

        
    } catch (err) {
        console.log(err)
        return res.status(500).json({ message: 'Error welcome email.'})
    }
}

```

### Exception/Log
```
__________ welcome email __________
{
  url: "/v3/marketing/lists'",
  method: 'GET',
  headers: {
    Authorization: 'Bearer << SENDGRID_API_KEY >>',
    'on-behalf-of': "The subuser's username. This header generates the API call as if the subuser account was making the call."
  }
}
Client {
  auth: 'Bearer << SENDGRID_API_KEY >>',
  impersonateSubuser: '',
  defaultHeaders: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
    'User-Agent': 'sendgrid/7.6.2;nodejs'
  },
  defaultRequest: {
    baseUrl: 'https://api.sendgrid.com/',
    url: '',
    method: 'GET',
    headers: {},
    maxContentLength: Infinity,
    maxBodyLength: Infinity
  },
  Client: [class Client]
}

 ERROR  Unauthorized

  at node_modules/@sendgrid/client/src/classes/client.js:146:29
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Technical details:
* sendgrid-nodejs version: 7.6.2
* node version: v14.18.0

**Comment by TomBell95** [comment]
## If required, below are my routes and index for the api folder...

### api/routes/contact.js
```
const { Router } = require('express')
const router = Router()

// Initialize Controller
const contactController = require('../controllers/contactController')


// POST contact form
router.post('/contact-form', contactController.contact)

// POST welcome email
router.get('/welcome-email', contactController.welcome)

module.exports = router
```


### api/index.js
```
const express = require('express')
const cors = require('cors')
const db = require('./db')


// Create express instanace
const app = express()

// Init body-parser options (inbuilt with express)
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());

// Require & Import API routes
...
const contact = require('./routes/contact')

// Use API Routes
...
app.use(contact)

// Export the server middleware
module.exports = {
  path: '/api',
  handler: app
}
```

**Comment by JenniferMah** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
