### ISSUE TITLE
randomly I hit unhandled error with  v7.4.5

### ISSUE THREAD

**Issue by radosi** [sendgrid/sendgrid-nodejs#1362]
randomly I got this in logs and my project crash .. 

{
    "error": {
        "message": "Bad Request",
        "code": 400,
        "response": {
            "headers": {
                "server": "nginx",
                "date": "Tue, 10 May 2022 09:31:05 GMT",
                "content-type": "application/json",
                "content-length": "288",
                "connection": "close",
                "access-control-allow-origin": "https://sendgrid.api-docs.io",
                "access-control-allow-methods": "POST",
                "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
                "access-control-max-age": "600",
                "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html",
                "strict-transport-security": "max-age=600; includeSubDomains"
            },
            "body": {
                "errors": [
                    {
                        "message": "The to array is required for all personalization objects, and must have at least one email object with a valid email address.",
                        "field": "personalizations.0.to",
                        "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"
                    }
                ]
            }
        }
    },
    "level": "error",
    "message": "uncaughtException: Bad Request\nError: Bad Request\n    at node_modules/@sendgrid/client/src/classes/client.js:146:29\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "stack": "Error: Bad Request\n    at node_modules/@sendgrid/client/src/classes/client.js:146:29\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "exception": true,
    "date": "Tue May 10 2022 09:31:05 GMT+0000 (Coordinated Universal Time)",
    "process": {
        "pid": 1,
        "uid": 0,
        "gid": 0,
        "cwd": "/usr/src/app",
        "execPath": "/usr/local/bin/node",
        "version": "v16.15.0",
        "argv": [
            "/usr/local/bin/node",
            "/usr/src/app/dist/app.js"
        ],
        "memoryUsage": {
            "rss": 170242048,
            "heapTotal": 92901376,
            "heapUsed": 86745416,
            "external": 1571856,
            "arrayBuffers": 508908
        }
    },
    "os": {
        "loadavg": [
            0.28,
            0.19,
            0.07
        ],
        "uptime": 218.32
    },
    "trace": [
        {
            "column": 29,
            "file": "node_modules/@sendgrid/client/src/classes/client.js",
            "function": null,
            "line": 146,
            "method": null,
            "native": false
        },
        {
            "column": 5,
            "file": "node:internal/process/task_queues",
            "function": "processTicksAndRejections",
            "line": 96,
            "method": null,
            "native": false
        }
    ]
}

**Comment by radosi** [comment]
Found the issue on my request .. but please handle this error on your side
