### ISSUE TITLE
handling JSONPARSE ERROR

### ISSUE THREAD

**Issue by madhums** [sendgrid/sendgrid-nodejs#188]
Hi guys, I get this error when sending some emails, is there anyway I could know what might be causing the error?

```
Error: SyntaxError: Unexpected token < JSONPARSEERROR when parsing: <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at Request._callback (/app/node_modules/sendgrid/lib/sendgrid.js:82:25)
    at Request.self.callback (/app/node_modules/sendgrid/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/app/node_modules/sendgrid/node_modules/request/request.js:1073:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/app/node_modules/sendgrid/node_modules/request/request.js:1019:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

I am sending an xlsx file

```js
  var email = new sendgrid.Email();

  email.addTo('to@email.com');
  email.setFrom('my@email.com');
  email.setSubject('Subject');
  email.setHtml('Excel export');
  email.addFile({
    filename: 'file.xlsx',
    content: new Buffer(excel, 'binary')
  });

  sendgrid.send(email, function (err) {
    if (err) {
      console.error(err);
      return callback(err);
    }
    console.log('Report emailed to to@email.com');
    callback();
  });
```

**Comment by tnilles** [comment]
Got the same error, with a simple email (no files attached).

I suspect it was an issue on sendgrid end, because they had 500 errors on the same day (check http://status.sendgrid.com/incidents/gjhgqntyqdqb, http://status.sendgrid.com/ for the issues history).

**Comment by thinkingserious** [comment]
@madhums,

If you are still experiencing this issue, please feel free to reopen this issue. Thanks!
