### ISSUE TITLE
Can't set headers after they've been sent

### ISSUE THREAD

**Issue by irthos** [sendgrid/sendgrid-nodejs#195]
Hi, this may be a newb question. Apologies. I need to send 2 emails after customer capture - one to the customer and one to the manager. I'm making two email objects within one post to /email api. both emails go through but heroku crashes with the error below. is that supposed to throw this error or is it a bug? I'll should probably just make two calls to the api or a seperate endpoint.

Thanks for any help :)

Here's my node code
        
    var email = new sendgrid.Email();
	email.addTo(req.body.to);
	email.setFrom('jeremy@telcobillcutters.com.au');
	email.setSubject(req.body.subject);
	email.setText(req.body.text);
	// email.addHeader('X-Sent-Using', 'SendGrid-API');
	email.setHeaders({'X-Transport': 'web'});

	sendgrid.send(email, function (err, json) {
		if (err) {
			return res.send("Problem Sending Email!!!!");
		}
		console.log(json);
		res.send("Email Sent OK!!!!");
	});

	setTimeout(function () {
		var emailSales = new sendgrid.Email();
		emailSales.addTo('irth03@gmail.com');
		emailSales.setFrom(req.body.to);
		emailSales.setSubject(req.body.subject);
		emailSales.setText(JSON.stringify(req.body.capture) + JSON.stringify(req.body.usage));
		emailSales.addHeader('X-Sent-Using', 'SendGrid-API');
		emailSales.addHeader('X-Transport', 'web');
		sendgrid.send(emailSales, function(err, json) {
			if (err) {
				return res.send("Problem Sending Email!!!!");
			}
			console.log(json);
			res.send("Email Sent OK!!!!");
		});
	}, 5000);

## log from herooku
...
{ message: 'success' }
2015-10-26T20:04:07.651382+00:00 heroku[router]: at=info method=POST path="/api/email" host=jtyree.herokuapp.com request_id=cff5ece1-87ce-4654-97d4-584540914c0e fwd="24.68.133.163" dyno=web.1 connect=0ms service=92ms status=200 bytes=212
2015-10-26T20:04:12.637299+00:00 app[web.1]: _http_outgoing.js:335
2015-10-26T20:04:12.637302+00:00 app[web.1]:     throw new Error('Can\'t set headers after they are sent.');
2015-10-26T20:04:12.637303+00:00 app[web.1]:           ^
2015-10-26T20:04:12.637304+00:00 app[web.1]: Error: Can't set headers after they are sent.
2015-10-26T20:04:12.637305+00:00 app[web.1]:     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
2015-10-26T20:04:12.637306+00:00 app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:718:10)
2015-10-26T20:04:12.637307+00:00 app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:163:12)
2015-10-26T20:04:12.637307+00:00 app[web.1]:     at /app/index.js:73:8
2015-10-26T20:04:12.637308+00:00 app[web.1]:     at Request._callback (/app/node_modules/sendgrid/lib/sendgrid.js:91:14)
2015-10-26T20:04:12.637309+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/sendgrid/node_modules/request/request.js:198:22)
2015-10-26T20:04:12.637310+00:00 app[web.1]:     at Request.emit (events.js:110:17)
2015-10-26T20:04:12.637310+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/sendgrid/node_modules/request/request.js:1082:10)
2015-10-26T20:04:12.637311+00:00 app[web.1]:     at Request.emit (events.js:129:20)
2015-10-26T20:04:12.637312+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/sendgrid/node_modules/request/request.js:1009:12)
2015-10-26T20:04:12.633042+00:00 app[web.1]: { message: 'success' }
2015-10-26T20:04:13.329736+00:00 heroku[web.1]: State changed from up to crashed
2015-10-26T20:04:13.310941+00:00 heroku[web.1]: Process exited with status 1

**Comment by tswaters** [comment]
You are calling `res.send` twice - the second time raises this error.

Try using something like `async` or promises to perform both sends and only perform the send call after both have been sent.

**Comment by thinkingserious** [comment]
Thanks for reaching out @irthos! Please feel free to reopen if you are still having issues.

Thanks for the solution @tswaters!
