### ISSUE TITLE
Error: options.uri is a required argument

### ISSUE THREAD

**Issue by pbrandt1** [sendgrid/sendgrid-nodejs#229]
There's an issue binding `this` in sendgrid.js send() method on line 54.  @gpoesia has already opened a PR to fix this https://github.com/sendgrid/sendgrid-nodejs/pull/209 (thanks, @gpoesia 😘).

```
Error: options.uri is a required argument
    at Request.init (/Users/peter/if/root/components/cinna-slack/chat/node_modules/request/request.js:244:31)
    at new Request (/Users/peter/if/root/components/cinna-slack/chat/node_modules/request/request.js:140:8)
    at request (/Users/peter/if/root/components/cinna-slack/chat/node_modules/request/index.js:55:10)
    at Function._send (/Users/peter/if/root/components/cinna-slack/chat/node_modules/sendgrid/lib/sendgrid.js:72:15)
    at Function.send (/Users/peter/if/root/components/cinna-slack/chat/node_modules/sendgrid/lib/sendgrid.js:54:21)
```

**Comment by thinkingserious** [comment]
Hello @pbrandt1,

I believe this will no longer be an issue in the new version of this library: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta. It will be out of beta in a few weeks.

However, I've left the PR open for verification. Please continue to follow that thread for updates.

Thank you for your support!

With Best Regards,

Elmer

**Comment by tylerjusfly** [comment]
![image](https://user-images.githubusercontent.com/53145644/143766043-8f54c499-e59e-47cc-b31f-28556da7ca12.png)
I JUST GOT INTO A SAME ERROR.

Any help?
