### ISSUE TITLE
Problem with package.json 

### ISSUE THREAD

**Issue by christianallred** [sendgrid/sendgrid-nodejs#289]
#### Issue Summary

Simply importing the library generates this bug when compiling with webpack .

ERROR in ./~/sendgrid/package.json
Module parse failed: C:\~\node_modules\sendgrid\package.json Unexpected token (2:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:10)
    at Parser.pp$4.raise (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\~\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\~\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\~\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\~\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\~\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\~\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.provide (C:\~\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (C:\~\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (C:\~\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (C:\~\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (C:\~\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (C:\~\node_modules\webpack\lib\NormalModule.js:84:14)
    at Compilation.buildModule (C:\~\node_modules\webpack\lib\Compilation.js:126:9)
    at C:\~\node_modules\webpack\lib\Compilation.js:309:10
    at C:\~\node_modules\webpack\lib\NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\~\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:69)
    at onDoneResolving (C:\~\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
    at onDoneResolving (C:\~\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
    at C:\~\node_modules\webpack\lib\NormalModuleFactory.js:116:7
    at C:\~\node_modules\webpack\node_modules\async\lib\async.js:726:13
    at C:\~\node_modules\webpack\node_modules\async\lib\async.js:52:16
 @ ./~/sendgrid/lib/sendgrid.js 7:10-38

**Comment by thinkingserious** [comment]
Hello @christianallred,

I'm putting this in our backlog to investigate deeper.

A brief investigation around `package.json Unexpected token` reveals that there may be an issue with the file encoding. I'm not sure how that happened though.

I am not familiar with webpack, so any information on how I could reproduce this would speed things along.

Thanks!

**Comment by finalfreq** [comment]
This isn't an issue on this repos end, your webpack config just needs a json loader, see this issue:

https://github.com/webpack/webpack/issues/303

I resolved myself adding `      { test: /\.json$/, loader: 'json'}` to my webpackloaders

**Comment by thinkingserious** [comment]
@finalfreq Thanks for jumping in with a solution!

Can you email us at dx@sendgrid.com so we can send you some swag? Just let us know your mailing address and T-shirt size.

**Comment by thinkingserious** [comment]
@christianallred,

Please let us know if you run into any other issues.
