### ISSUE TITLE
Problem sending bulk email along with substitutions

### ISSUE THREAD

**Issue by utkarsh-var** [sendgrid/sendgrid-nodejs#398]
#### Issue Summary

While trying to send bulk emails, I want to personalize individual email by their first name etc by using substitutions. I'm setting firstName array under 'sub' and sending the request to mail API but it's throwing the error- SendGridError: Response error

Here is the stack trace of the error-

"error":"SendGridError: Response error\n    at /node_modules/sendgrid/lib/sendgrid.js:104:23\n    at IncomingMessage.<anonymous> (/node_modules/sendgrid-rest/lib/client.js:108:9)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"

Here is the function that I'm using-

``` 
const from = "mail@example.com";
const to = ["email1@example.com",  "email2@example.com"];
const TEMPLATE_ID = "some_template_id";
const substititions = {"-firstName-": ["name1", "name2"]};
const subject = "Testing bulk email";
sendMail(from, to, TEMPLATE_ID, substitutions, subject);

function sendMail(from ,to, TEMPLATE_ID, substitutions, subject) {
    var request = sendgrid.emptyRequest({
        method: 'POST',
        path: '/v3/mail/send',
        body: {
            'personalizations': [
                {
                    'to': to,
                    'sub': substitutions,
                    'subject': subject
                }
            ],
            'from': {
                'email': from
            },
            'template_id': TEMPLATE_ID
        }
    });

    return sendgrid.API(request);

}

```

#### Refrences:-
These are the two links that I've followed-
[sendgrid API Reference](https://sendgrid.com/docs/API_Reference/SMTP_API/index.html)
[sendgrid nodejs lib without mail helper class](https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional_templates)

#### Technical details:

* sendgrid Version: 5.0.1
* Node.js Version: 6.9.5

**Comment by thinkingserious** [comment]
Hello @utkarsh-var,

[Here is a full example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional_templates) of using a template with substitutions.

You can obtain the underlying error [like so](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error).

Please take a look and let me know how it goes.

Thanks!

With Best Regards,

Elmer

**Comment by utkarsh-var** [comment]
Thanks for replying @thinkingserious 

I tried it using Without Mail Helper Class, I am getting following error:-
```
{
    "message": "Response error",
    "response": {
        "statusCode": 400,
        "body": {
            "errors": [
                {
                    "message": "Invalid type. Expected: object, given: string.",
                    "field": "personalizations.0.to.0",
                    "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"
                }
            ]
        },
        "headers": {
            "server": "nginx",
            "date": "Wed, 28 Jun 2017 08:21:18 GMT",
            "content-type": "application/json",
            "content-length": "211",
            "connection": "close",
            "x-frame-options": "DENY",
            "access-control-allow-origin": "https://sendgrid.api-docs.io",
            "access-control-allow-methods": "POST",
            "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
            "access-control-max-age": "600",
            "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html"
        }
    }
}
```

Here is the code:-
```
test(req, res) {
        const from = "from@example.com";
        const to = ["to@example.com"];
        const substitutions = {"-firstName-": ["utkarsh"]};
        const subject = "Testing bulk emails";
        sendMail(from, to, template.emailVerification, substitutions, subject)
                .then(function (response) {
                    res.status(response.statusCode).send({
                        messsage: 'Mail sent'
                    });
                })
                .catch(function (error) {
                    res.status(error.response.statusCode).send(error);
                });
    }

function sendMail(from ,to, TEMPLATE_ID, substitutions, subject) {
    var request = sendgrid.emptyRequest({
        method: 'POST',
        path: '/v3/mail/send',
        body: {
            'personalizations': [
                {
                    'to': to,
                    'substitutions': substitutions,
                    'subject': subject
                }
            ],
            'from': {
                'email': from
            },
            'template_id': TEMPLATE_ID
        }
    });

    return sendgrid.API(request);

}
```
Could you look into it and let me know what am I doing wrong.

**Comment by thinkingserious** [comment]
Can you try changing: `const to = ["to@example.com"];` to `const to = "to@example.com";`

**Comment by utkarsh-var** [comment]
@thinkingserious I did tried changing `const to = ["to@example.com"]; to const to = "to@example.com";` but it's giving same error.

**Comment by thinkingserious** [comment]
Ah, I see, the `to` object needs to be in the following format:

```javascript
        to: [
          {
            email: 'test@example.com',
          },
        ]
```

In the first case, you had:

```javascript
        to: [
            'test@example.com',
        ]
```

And then, just now you had:

```javascript
        to: 'test@example.com'
```

Please update your `to` object accordingly. Thanks!

**Comment by utkarsh-var** [comment]
I tried `to` object in both 
```
to: [
   {
      email: 'test@example.com'
   }
]
```
and 
```
to: [
   'test@example.com'
]
```
formats but it's giving same error.

**Comment by thinkingserious** [comment]
I think it should be:

```javascript
to: [
   {
      email: 'test@example.com',
   },
]
```

**Comment by utkarsh-var** [comment]
If I am doing 
```
test(req, res) {
        const from = "from@example.com";
        const to = "to@example.com";
        const substitutions = {"-firstName-": "utkarsh"};
        const subject = "Testing bulk emails";
        sendMail(from, to, template.emailVerification, substitutions, subject)
                .then(function (response) {
                    res.status(response.statusCode).send({
                        messsage: 'Mail sent'
                    });
                })
                .catch(function (error) {
                    res.status(error.response.statusCode).send(error);
                });
    }

function sendMail(from ,to, TEMPLATE_ID, substitutions, subject) {
    var request = sendgrid.emptyRequest({
        method: 'POST',
        path: '/v3/mail/send',
        body: {
            'personalizations': [
                {
                    'to': [
                        {
                            'email': to
                        }
                    ],
                    'substitutions': substitutions,
                    'subject': subject
                }
            ],
            'from': {
                'email': from
            },
            'template_id': TEMPLATE_ID
        }
    });

    return sendgrid.API(request);

}
````
I am able to send mail, but as mentioned above I want to send bulk emails with substitutions.

**Comment by utkarsh-var** [comment]
I tried 
```
test(req, res) {
        const from = "from@example.com";
        const to = [
            {
                email: 'test1@example.com'
            },
            {
                email: 'test2@example.com'
            }
        ];
        const substitutions = {"-firstName-": ["name1", "name2"]};
        const subject = "Testing bulk emails";
        sendMail(from, to, template.emailVerification, substitutions, subject)
                .then(function (response) {
                    res.status(response.statusCode).send({
                        messsage: 'Mail sent'
                    });
                })
                .catch(function (error) {
                    res.status(error.response.statusCode).send(error);
                });
    }

function sendMail(from ,to, TEMPLATE_ID, substitutions, subject) {
    var request = sendgrid.emptyRequest({
        method: 'POST',
        path: '/v3/mail/send',
        body: {
            'personalizations': [
                {
                    'to': to,
                    'substitutions': substitutions,
                    'subject': subject
                }
            ],
            'from': {
                'email': from
            },
            'template_id': TEMPLATE_ID
        }
    });

    return sendgrid.API(request);

}
```
It's throwing following error-
```
{
    "message": "Response error",
    "response": {
        "statusCode": 400,
        "body": {
            "errors": [
                {
                    "message": "Bad Request",
                    "field": null,
                    "help": null
                }
            ]
        },
        "headers": {
            "server": "nginx",
            "date": "Wed, 28 Jun 2017 17:09:53 GMT",
            "content-type": "application/json",
            "content-length": "63",
            "connection": "close",
            "x-frame-options": "DENY",
            "access-control-allow-origin": "https://sendgrid.api-docs.io",
            "access-control-allow-methods": "POST",
            "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
            "access-control-max-age": "600",
            "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html"
        }
    }
}
```

**Comment by thinkingserious** [comment]
Can you please grab the underlying message, [like so](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error-messages)?

It looks like the error is probably related to substitutions, which should be in this format:

```javascript
'substitutions': {
          '-name-': 'Example User',
          '-city-': 'Denver',
        }
```

**Comment by utkarsh-var** [comment]
@thinkingserious I am able to send the single email with substitutions as mentioned above. The problem is coming when I want to send bulk emails with substitutions. I am properly setting `to` array, and `substitutions` object as I have posted above. But it's throwing an error. I guess **Mail Helper Class** doesn't have any method to set an array of **to_email**. And Without Mail Helper Class it's throwing an error. Could you provide me a working solution for **sending bulk emails with substitutions.**

**Comment by thinkingserious** [comment]
Hi @utkarsh-var,

I believe [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15) should help.

Please let me know if you continue to run into trouble.

With Best Regards,

Elmer

**Comment by utkarsh-var** [comment]
Hi @thinkingserious,

I tried all the examples and suggestions that you have given, but it's not working in my case. I have been stuck with this issue since last 10 days. It would be helpful if you connect me with someone who could solve this issue. Or we can discuss this issue on skype call if it works for you. It's urgent. 

Regards!
Utkarsh

**Comment by thinkingserious** [comment]
Hi @utkarsh-var,

Were you able to get the [underlying error message](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error-messages)?

Could you post the latest code you have tried?

Thanks!

Elmer

**Comment by utkarsh-var** [comment]
Finally got it working, below is my solution-

```
test(req, res, next) {
        const to = ["email1@example.com", "email2@example.com"];
        const substitutions = [
            {"-firstName-": "name1", "-url-": "https://google.com"},
            {"-firstName-": "name2", "-url-": "https://facebook.com"}
        ];
        const subject = "Test Email";
        sendMail(from, to, template.emailVerification, substitutions, subject)
            .then(function(response) {
                res.status(response.statusCode).send({
                    messsage: 'Mail sent'
                });
            })
            .catch((error) => {
                return next(error);
            });
    }

function sendMail(from ,to, TEMPLATE_ID, substitutions, subject) {
    const personalizations = [];
    for (var i = 0; i < to.length; i++) {
        personalizations[i] = {
            'to': [
                {
                    'email': to[i]
                }
            ],
            'substitutions': substitutions[i]
        }
    }

    var request = sendgrid.emptyRequest({
        method: 'POST',
        path: '/v3/mail/send',
        body: {
            'personalizations': personalizations,
            'from': {
                'email': from
            },
            'template_id': TEMPLATE_ID
        }
    });

    return sendgrid.API(request);

}
```

**Comment by thinkingserious** [comment]
Awesome! 

Thanks for sharing the solution with us @utkarsh-var!
