### ISSUE TITLE
Sending error in heroku environment

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [sendgrid/sendgrid-nodejs#663]
Hello,
I'm with the following code
```javascript
'use strict'

import path from 'path'
import EmailTemplates from 'email-templates'
import { defaultConfig, isProduction, isTest } from '../../utils'
import { info, error } from '../../logger'

const mailerUser = process.env.MAILER_USER || defaultConfig.mailer.user
const mailerKey = process.env.MAILER_KEY || defaultConfig.mailer.key

const sg = require('sendgrid')(mailerKey)
const { Email, Content, Mail } = require('sendgrid').mail

const root = path.resolve(__dirname, '../../..', 'views/mailer')

export const sendOne = async (templateName, locals) => {
  try {
    if (!locals.email) {
      throw new Error('email address required')
    }

    if (!locals.subject) {
      throw new Error('subject required')
    }

    if (!locals.fromEmail) {
      locals.fromEmail = mailerUser
    }

    if (!templateName) {
      throw new Error('html template required')
    }

    const email = new EmailTemplates({
      views: { root },
      transport: {
        jsonTransport: true
      }
    })
    const html = await email.render(templateName, locals)

    // if we are testing don't send out an email instead return
    // success and the html for inspection
    if (isTest) {
      return {
        responseStatus: '250 2.0.0 OK 1350452502 s5sm19782310obo.10',
        html
      }
    }

    const fromEmail = new Email(locals.fromEmail, 'Inovadoc')
    const toEmail = new Email(locals.email)
    const content = new Content('text/html', html)
    const mail = new Mail(fromEmail, locals.subject, toEmail, content)

    const request = sg.emptyRequest({
      method: 'POST',
      path: '/v3/mail/send',
      body: mail.toJSON()
    })

    console.log('mail.toJSON()>>>>>>>', mail.toJSON())

    sg.API(request, (err, response) => {
      if (err) {
        console.log('err>>>>>>', err)
        throw err
      }
      if (!isProduction) {
        info('Mailer', JSON.stringify(response.headers))
        info('Mailer', response.statusCode)
      }
    })
  } catch (err) {
    error('Mailer', `Error send email`, err)
  }
}
```
The sending html is being processed correctly with the parameters being changed as well. 
```
2018-03-08T19:08:04.577846+00:00 app[web.1]: mail.toJSON()>>>>>>> { from: { email: 'donotreply@inovadoc.com', name: 'Inovadoc' },
2018-03-08T19:08:04.577848+00:00 app[web.1]:   personalizations:
2018-03-08T19:08:04.577849+00:00 app[web.1]:    [ { to: [Array],
2018-03-08T19:08:04.577850+00:00 app[web.1]:        cc: undefined,
2018-03-08T19:08:04.577852+00:00 app[web.1]:        bcc: undefined,
2018-03-08T19:08:04.577853+00:00 app[web.1]:        subject: undefined,
2018-03-08T19:08:04.577854+00:00 app[web.1]:        headers: undefined,
2018-03-08T19:08:04.577855+00:00 app[web.1]:        substitutions: undefined,
2018-03-08T19:08:04.577856+00:00 app[web.1]:        custom_args: undefined,
2018-03-08T19:08:04.577858+00:00 app[web.1]:        send_at: undefined } ],
2018-03-08T19:08:04.577859+00:00 app[web.1]:   subject: 'Bem vindo ao Inovadoc',
2018-03-08T19:08:04.577860+00:00 app[web.1]:   content:
2018-03-08T19:08:04.577861+00:00 app[web.1]:    [ { type: 'text/html',
2018-03-08T19:08:04.577889+00:00 app[web.1]:        value: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><head><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>Bem vindo ao Inovadoc!</title><style>\n@media only screen and (max-width: 640px) {\n  body {\n    padding: 0 !important;\n  }\n\n  h1,\nh2,\nh3,\nh4 {\n    font-weight: 800 !important;\n    margin: 20px 0 5px !important;\n  }\n\n  h1 {\n    font-size: 22px !important;\n  }\n\n  h2 {\n    font-size: 18px !important;\n  }\n\n  h3 {\n    font-size: 16px !important;\n  }\n\n  .container {\n    padding: 0 !important;\n    width: 100% !important;\n  }\n\n  .content {\n    padding: 0 !important;\n  }\n\n  .content-wrap {\n    padding: 10px !important;\n  }\n\n  .invoice {\n    width: 100% !important;\n  }\n}\n</style></head><body itemscope="" itemtype="http://schema.org/EmailMessage" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; height: 100%; line-height: 1.6em; background-color: #ecf0f5; color: #6c7b88; width: 100% !important;"><table class="body-wrap" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; background-color: #ecf0f5; width: 100%;" width="100%" bgcolor="#ecf0f5"><tbody style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top;" valign="top"></td><td class="container" width="600" style="font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; margin: 0 auto !important; clear: both !important;" valign="top"><div class="content" style="font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; margin: 0 auto; display: block; padding: 20px;"><table class="main" width="100%" cellpadding="0" cellspacing="0" itemprop="action" itemscope="" itemtype="http://schema.org/ConfirmAction" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; background-color: #fff; border-bottom: 2px solid #d7d7d7;" bgcolor="#fff"><tbody style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="content-wrap" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 20px;" valign="top"><meta itemprop="name" content="Confirm Email"><table width="100%" cellpadding="0" cellspacing="0" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><tbody style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top;" valign="top"></td></tr><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="content-block" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top"><h3 style="box-sizing: border-box; font-family: \'Helvetica Neue\', Helvetica, Arial, \'Lucida Grande\', sans-serif; color: #1a2c3f; margin: 30px 0 0; line-height: 1.2em; font-weight: 400; font-size: 18px;">Bem vindo ao Inovadoc!</h3></td></tr><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="content-block" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top">Confirme seu endereço de e-mail clicando no link abaixo.</td></tr><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="content-block" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top">Nós podemos precisar enviar-lhe informações importantes sobre os nossos serviços e é imprescindível ter um endereço de e-mail válido.</td></tr><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="content-block aligncenter" itemprop="handler" itemscope="" itemtype="http://schema.org/HttpActionHandler" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px; text-align: center;" valign="top" align="center"><a class="btn-primary" href="http://accounts-inovadoc.herokuapp.com/confirmation?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25maXJtYXRpb25Ub2tlbiI6ImJiZjFiZmNiMDkyN2NlY2Q3NDkzMzA2YWQwMzQwMDRiMjc3MDFhOTNmOTM2MDI3NjMxYzAwNmRmZmM2ODU0ZmQiLCJpYXQiOjE1MjA1MzYwODMsImV4cCI6MTUyMDc5NTI4M30.3u0oBGrTNNjrnAUarGiG5BaECKUwXMguBpDNkd_Gmfo" itemprop="url" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; text-decoration: none; color: #FFF; background-color: #42A5F5; border: solid #42A5F5; border-width: 10px 20px; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; text-transform: capitalize;">Confirmar endereço de email</a></td></tr><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top;" valign="top"></td></tr><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="content-block" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top">Atenciosamente<br style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;">— Equipe Inovadoc</td></tr></tbody></table></td></tr></tbody></table><div class="footer" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; padding: 20px;"><table width="100%" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><tbody style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><tr style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px;"><td class="aligncenter content-block" style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; vertical-align: top; padding: 0 0 20px; text-align: center; color: #999; font-size: 12px;" valign="top" align="center">Copyright © 2018 Inovadoc, Inc.</td></tr></tbody></table></div></div></td><td style="margin: 0; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top;" valign="top"></td></tr></tbody></table></body></html>' } ],
2018-03-08T19:08:04.577891+00:00 app[web.1]:   attachments: undefined,
2018-03-08T19:08:04.577892+00:00 app[web.1]:   template_id: undefined,
2018-03-08T19:08:04.577893+00:00 app[web.1]:   sections: undefined,
2018-03-08T19:08:04.577894+00:00 app[web.1]:   headers: undefined,
2018-03-08T19:08:04.577895+00:00 app[web.1]:   categories: undefined,
2018-03-08T19:08:04.577896+00:00 app[web.1]:   custom_args: undefined,
2018-03-08T19:08:04.577897+00:00 app[web.1]:   send_at: undefined,
2018-03-08T19:08:04.577898+00:00 app[web.1]:   batch_id: undefined,
2018-03-08T19:08:04.577900+00:00 app[web.1]:   asm: undefined,
2018-03-08T19:08:04.577901+00:00 app[web.1]:   ip_pool_name: undefined,
2018-03-08T19:08:04.577902+00:00 app[web.1]:   mail_settings: undefined,
2018-03-08T19:08:04.577903+00:00 app[web.1]:   tracking_settings: undefined,
2018-03-08T19:08:04.577904+00:00 app[web.1]:   reply_to: undefined }
```
When sendgrid tries to send I get the following exception
```
2018-03-08T19:08:04.654640+00:00 app[web.1]: err>>>>>> { SendGridError: Response error
2018-03-08T19:08:04.654645+00:00 app[web.1]:     at /app/node_modules/sendgrid/lib/sendgrid.js:123:19
2018-03-08T19:08:04.654647+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/sendgrid-rest/lib/client.js:112:9)
2018-03-08T19:08:04.654651+00:00 app[web.1]:     at emitNone (events.js:111:20)
2018-03-08T19:08:04.654654+00:00 app[web.1]:     at IncomingMessage.emit (events.js:208:7)
2018-03-08T19:08:04.654656+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1064:12)
2018-03-08T19:08:04.654657+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-03-08T19:08:04.654659+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-03-08T19:08:04.654661+00:00 app[web.1]:   message: 'Response error',
2018-03-08T19:08:04.654663+00:00 app[web.1]:   response:
2018-03-08T19:08:04.654666+00:00 app[web.1]:    { statusCode: 401,
2018-03-08T19:08:04.654667+00:00 app[web.1]:      body: '',
2018-03-08T19:08:04.654669+00:00 app[web.1]:      headers:
2018-03-08T19:08:04.654671+00:00 app[web.1]:       { server: 'nginx',
2018-03-08T19:08:04.654672+00:00 app[web.1]:         date: 'Thu, 08 Mar 2018 19:08:04 GMT',
2018-03-08T19:08:04.654674+00:00 app[web.1]:         'content-type': 'application/json',
2018-03-08T19:08:04.654676+00:00 app[web.1]:         'content-length': '116',
2018-03-08T19:08:04.654677+00:00 app[web.1]:         connection: 'close',
2018-03-08T19:08:04.654679+00:00 app[web.1]:         'access-control-allow-origin': 'https://sendgrid.api-docs.io',
2018-03-08T19:08:04.654681+00:00 app[web.1]:         'access-control-allow-methods': 'POST',
2018-03-08T19:08:04.654683+00:00 app[web.1]:         'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
2018-03-08T19:08:04.654685+00:00 app[web.1]:         'access-control-max-age': '600',
2018-03-08T19:08:04.654686+00:00 app[web.1]:         'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' } } }
```
however, local development is able to send the emails correctly. Only the heroku environment is experiencing this problem!

### Environment
Node.js: 8.9.3
restify:  6.3.4
Sendgrid: 5.2.3

**Comment by thinkingserious** [comment]
Hi @carvalhoviniciusluiz,

It looks like there is a problem with reading your SendGrid credentials on Heroku. I would verify that the key is actually being set.

Also, I suggest you upgrade to the [newest version of this SDK](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail), it is much easier to work with and the version you are using is deprecated.

With Best Regards,

Elmer

**Comment by carvalhoviniciusluiz** [comment]
I'm using the version available at npm https://www.npmjs.com/package/sendgrid

I did not know that version was obsolete. What library should be used on the nodejs, has it in npm?

**Comment by thinkingserious** [comment]
Here it is: https://www.npmjs.com/package/@sendgrid/mail

Thanks!
