### ISSUE TITLE
bad request when i send with attachment 

### ISSUE THREAD

**Issue by JongSikLim** [sendgrid/sendgrid-nodejs#769]
#### Issue Summary

I just follow the attachment docs, but bad request error is occurred.

+a ) i want attach json object to files. What should i do?

#### Steps to Reproduce
1. I sign up sendgrid.
2. I receive apikey and copy the code, paste in my workplace.
3. without attachment, it works fine. but with attachment it isnt work.
 ```
   const sgMail = require('@sendgrid/mail');
    process.env.SENDGRID_API_KEY='<my key>';
    sgMail.setApiKey(process.env.SENDGRID_API_KEY);
    

    const msg = {
      to: 'recipient@example.org',
      from: 'sender@example.org',
      subject: 'Hello attachment',
      html: '<p>Here’s an attachment for you!</p>',
      attachments: [
        {
          content: 'Some base 64 encoded attachment content',
          filename: 'some-attachment.txt',
          type: 'plain/text'
        }
      ]
    };
```

    sgMail.send(msg);

 and this is my error console

Uncaught (in promise) ResponseError: Bad Request
    at Request.http [as _callback] (C:\workspace\ShipSideApp\node_modules\@sendgrid\client\src\classes\client.js:124:25)
    at Request.self.callback (C:\workspace\ShipSideApp\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\workspace\ShipSideApp\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\workspace\ShipSideApp\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

#### Technical details:

* sendgrid-nodejs Version: latest version
* Node.js Version: 8.11.4
* Using electron.

**Comment by aroach** [comment]
I believe you need to actually base64 encode the string you have in the `content` field.  Here's a StackOverflow with that information https://stackoverflow.com/questions/6182315/how-to-do-base64-encoding-in-node-js#6182519

**Comment by JongSikLim** [comment]
Thanks you for your comment
