### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by cdoyle429** [sendgrid/sendgrid-nodejs#859]
#### Issue Summary

I am just getting started with sendgrid and I am struggling to send emails. I am getting the following error: 

(node:3212) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Request.http [as _callback] (C:\Users\1444728\Documents\sendgrid\node_modules\@sendgrid\client\src\classes\client.js:124:25)
    at Request.self.callback (C:\Users\1444728\Documents\sendgrid\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\1444728\Documents\sendgrid\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\1444728\Documents\sendgrid\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise
 which was not handled with .catch(). (rejection id: 1)
(node:3212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
 exit code.

#### Steps to Reproduce

The code I am using is: 

sgMail = require('@sendgrid/mail');
sgMailApiKey = MY_API_KEY;

sgMail.setApiKey(sgMailApiKey);
        const msg = {
          to: 'example@mail.com',
          from: 'another_example@mail.com',
          subject: 'Testing',
          text: 'Testing'
        };
        sgMail.send(msg);

#### Technical details:

* @sendgrid/mail Version: 6.3.1
* Node.js Version: 10.12.0

**Comment by aroach** [comment]
Hi @cdoyle429 -- thanks for giving us a go!

Generally a Bad Request indicates something is wrong with the JSON that is being sent to the server.

The only material difference between what you've provided above and the example below is that you haven't supplied the `html` property[1].  Try adding that and see if it works, and let us know.

https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail#quick-start-hello-email

[1] Note that I think it's required unless you disable the Plain Content setting: https://app.sendgrid.com/settings/mail_settings

**Comment by cdoyle429** [comment]
I have tried with the html property also and I am still getting the issue

**Comment by aroach** [comment]
I've copied the code that you pasted above, and your code is working for me.  I'm using the same versions of the library and node as you.

**Comment by cdoyle429** [comment]
I was running this on my work laptop. I replicated this on my personal laptop and did not have an issue. So the problem probably lies in the permissions on my laptop or proxy settings.

Thanks!

**Comment by aroach** [comment]
Ok cool. Thx for the update. Proxy crossed my mind but wasn’t sure how you
were running things.

**Comment by AWR14** [comment]
i've got the same problem, what permissions or proxy setting would i have to check on macbook?
