### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Unauthorized

### ISSUE THREAD

**Issue by mujsann** [sendgrid/sendgrid-nodejs#888]
I keep getting the error below while integrating Sendgrid SMTP/API 
I've tried changing the API keys and sender emails severally. I've even tried hardcoding the Api key as an arg for the sendGrid.setApiKey method. This is not the first time I'm using sendgrid for a project and I've never had this issue before.

"(node:35908) UnhandledPromiseRejectionWarning: Error: Unauthorized Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
[0] at Request.self.callback (node_modules/request/request.js:185:22)
[0] at Request.emit (events.js:182:13)
[0] at Request. (node_modules/request/request.js:1161:10)
[0] at Request.emit (events.js:182:13)
[0] at IncomingMessage. (node_modules/request/request.js:1083:12)
[0] at Object.onceWrapper (events.js:273:13)
[0] at IncomingMessage.emit (events.js:187:15)
[0] at endReadableNT (_stream_readable.js:1081:12)
[0] at process._tickCallback (internal/process/next_tick.js:63:19)
[0] (node:1618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asyncfunction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:1618) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: 10.4.1

**Comment by thinkingserious** [comment]
Hello @mujsann,

To rule out the API key, please try a simple cUrl request, [like so](https://sendgrid.com/docs/for-developers/sending-email/curl-examples/).

If that works, then please provide the code you are using that generates this error so that we can try to duplicate.

Thank you!

With Best Regards,

Elmer

**Comment by jns4u** [comment]
Once use this code snippet to resolve this issue. Working fine on Node 8 and above

let options = { method: 'POST',
      url: 'https://api.sendgrid.com/v3/mail/send',
      headers: 
       { 
         'cache-control': 'no-cache',
         'Content-Type': 'application/json',
         authorization: 'Bearer your_api_key' },
      body: 
       { personalizations: [ { to: [ { email: 'recepient_email' } ] } ],
         from: { email: 'sender_email' },
         subject: 'sendgrid mail data',
         content: 
          [ { type: 'text/plain',
              value: 'Sending this mail from sendgrid server!' } ] },
      json: true };

    request(options, function (error, response, body) {
      if (error) throw new Error(error);

      console.log(body);
    })

**Comment by soham04** [comment]
any update on this @mujsann @thinkingserious @childish-sambino @jns4u
