### ISSUE TITLE
Bad Request Request.http error while sending data as attachement 

### ISSUE THREAD

**Issue by amitbravo** [sendgrid/sendgrid-nodejs#895]
I collect data from firebase database and want to send it as xlsx file to user's email address. 
I got error something like 
````
Error: Bad Request
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
````
I wrote following cloud function 
````
const admin = require('firebase-admin');
const functions = require('firebase-functions');
var json2xls = require('json2xls');
const fs = require('fs');
const os = require('os');
const path = require('path');
var Buffer = require('buffer/').Buffer
const sgMail = require('@sendgrid/mail');
module.exports = function(req, res) {
  var users = []
  var filename;
admin.database().ref(`users`).once('value')
  .then(allusers => {
        allusers.forEach(user => {
          users.push({
            first_name: user.val().first_name,
            last_name: user.val().last_name,
            phone1: user.val().phone1
          })
        })
    })
    .then(()=>{
      var xls = json2xls(users);
      filename = path.join(os.tmpdir(),'data.xlsx')
      fs.writeFileSync(filename, xls, 'binary');
 var bitmap = fs.readFileSync(filename);
      var base64_encode =  Buffer(bitmap).toString("base64");
        console.log('base64_encode',base64_encode)
        sgMail.setApiKey(functions.config().sendgrid.key) //api key
const msg = {
          to: 'hisemail@gmail.com',
          from: 'myemail@gmail.com',
          subject: 'Sending with SendGrid is Fun',
          text: 'and easy to do anywhere, even with Node.js',
          html: '<strong>and easy to do anywhere, even with Node.js</strong>',
          content:[
            {
               type : 'string',
               value : 'message'
            }
          ],
          attachments: [
            {
              filename: 'data.xlsx',
              content: base64_encode,
              contentId: 'data.xlsx',
              disposition: "attachment"
            }
          ],
        };

        // sample test code which is working fine
        // const msg = {
        //   to: 'hisemail@gmail.com',
        //   from: 'myemail@gmail.com',
        //   subject: 'Sending with SendGrid is Fun 2',
        //   text: 'and easy to do anywhere, even with Node.js',
        //   html: '<strong>and easy to do anywhere, even with Node.js</strong>',
        // };
 sgMail.send(msg);
  })
    .catch(error => {
      console.log('error',error)
    })
 res.send({ status: 'OK' })
}
````

**Comment by aroach** [comment]
Perhaps try removing the `content` array in the `msg` object.  Let us know if that worked.

**Comment by amitbravo** [comment]
1. Main thing was use only that email as from: which used to create sendgrid account.
2. removed content 
3. added    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',

**Comment by Maxstgt** [comment]
Got a CORS error in the frontend and in firebase I got the same error you described, thanks to you, I finally got rid of it! Thanks!
