### ISSUE TITLE
TypeError: Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by darkterra** [sendgrid/sendgrid-nodejs#903]
#### Issue Summary

I'm trying to send an email from my backend. When I get to the sendgrid.send-function, my server crashes with the following:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'client' of undefined
    at setApiKey (/home/jeremy/Documents/Workspace/assetregister-server/node_modules/@sendgrid/mail/src/classes/mail-service.js:35:10)
    at /home/jeremy/Documents/Workspace/assetregister-server/dist/models/user.js:184:27
    at nextTask (/home/jeremy/Documents/Workspace/assetregister-server/node_modules/async/dist/async.js:5324:14)
    at next (/home/jeremy/Documents/Workspace/assetregister-server/node_modules/async/dist/async.js:5331:9)
    at /home/jeremy/Documents/Workspace/assetregister-server/node_modules/async/dist/async.js:969:16
    at /home/jeremy/Documents/Workspace/assetregister-server/dist/models/user.js:176:11
    at /home/jeremy/Documents/Workspace/assetregister-server/node_modules/mongoose/lib/model.js:4698:16
    at /home/jeremy/Documents/Workspace/assetregister-server/node_modules/mongoose/lib/utils.js:263:16
    at model.$__save.error (/home/jeremy/Documents/Workspace/assetregister-server/node_modules/mongoose/lib/model.js:479:7)
    at /home/jeremy/Documents/Workspace/assetregister-server/node_modules/kareem/index.js:315:21
    at next (/home/jeremy/Documents/Workspace/assetregister-server/node_modules/kareem/index.js:209:27)
    at /home/jeremy/Documents/Workspace/assetregister-server/node_modules/kareem/index.js:182:9
    at process.nextTick (/home/jeremy/Documents/Workspace/assetregister-server/node_modules/kareem/index.js:499:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
#### Steps to Reproduce

1. Install @sendgrid/mail@6.3.1
2. Import setApiKey and send from @sendgrid/mail
3. Call `setApiKey` with the api key parameter
4. Call `send` with the message object

installed the sendgrid-nodejs npm package
Imported var SendGrid = require('sendgrid-nodejs').SendGrid; in my class
Set var sendgrid = new SendGrid("sendgrid username here", "api key here");

And then running:
```
import { setApiKey, send } from '@sendgrid/mail';

setApiKey(config.mail_server_settings.api_key)

const msg = {
  to: user.email,
  from: {
    name: 'The Sengrid Mailer',
    email: 'sendgridMailer@fromFakeSendgridmailer.fr',
  },
  subject: 'New mail for you !',
  text: 'This is my message !',
};

send(msg, function(err, data) {
  if (err) {
    console.error(err);
  };
```

#### Technical details:

* Node.js Version: 10.15.1

**Comment by thinkingserious** [comment]
Hello @darkterra,

What happens when you run [this code](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#send-a-single-email-to-a-single-recipient)?

With Best Regards,

Elmer

**Comment by bradtaniguchi** [comment]
I had the following giving me the same error in my TS code:
```typescript
import { setApiKey } from '@sendgrid/mail';
//..
setApiKey(config.mail_server_settings.api_key)
```

I was able to fix this in Typescript by just doing the following:
```typescript
import * as sendgrid from '@sendgrid/mail';
//...
sendgrid.setApiKey(apiKey);
```

**Comment by Nditah** [comment]
```ts
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import sendgrid from '@sendgrid/mail';
import { SendgridConfig } from 'src/configs/config.interface';

@Injectable()
export class SendgridService {
  private sendgridConfig: SendgridConfig;

  constructor(private readonly configService: ConfigService) {
    this.sendgridConfig = this.configService.get<SendgridConfig>('sendgrid');
    const { apiKey } = this.sendgridConfig;
    sendgrid.setApiKey(apiKey);
  }

  async sendMail(mail: sendgrid.MailDataRequired) {
    try {
      if (!mail.from) mail.from = this.sendgridConfig.senderEmail;
      const transport = await sendgrid.send(mail);
      return transport;
    } catch (err) {
      console.log(`Email successfully dispatched to ${err.message}`);
      throw new Error(err.message);
    }
  }
}

```

**Comment by bradtaniguchi** [comment]
@Nditah Did you try the alternate import of:
```
import * as sendgrid from '@sendgrid/mail';
```

**Comment by Nditah** [comment]
@bradtaniguchi   it didn't work for me. 
What I shared above worked perfectly. I shared it hoping someone will benefit.
Thanks

**Comment by bradtaniguchi** [comment]
Ah that wasn't clear to me I thought it **wasn't* working 👍🏼
