### ISSUE TITLE
Trouble sending email using @sendgrid/mail

### ISSUE THREAD

**Issue by ajgomezrivera** [sendgrid/sendgrid-nodejs#930]
#### Issue Summary

I'm using firebase functions to send an email once a user is created. I've copied the function from another of my applications, which works well, and in this application I can't send the email. 

This is the error I get:
"TypeError: Object.values is not a function
    at Mail.setDynamicTemplateData (/user_code/node_modules/@sendgrid/mail/node_modules/@sendgrid/helpers/classes/mail.js:342:12)
    at Mail.fromData (/user_code/node_modules/@sendgrid/mail/node_modules/@sendgrid/helpers/classes/mail.js:91:12)
    at new Mail (/user_code/node_modules/@sendgrid/mail/node_modules/@sendgrid/helpers/classes/mail.js:44:12)
    at Function.create (/user_code/node_modules/@sendgrid/mail/node_modules/@sendgrid/helpers/classes/mail.js:627:12)
    at MailService.send (/user_code/node_modules/@sendgrid/mail/src/classes/mail-service.js:174:25)
    at admin.auth.generateEmailVerificationLink.then (/user_code/lib/users/index.js:69:27)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"

Any idea what's this error and how to handle it?

#### Steps to Reproduce

const sgMail = require('@sendgrid/mail');
sgMail.setApiKey('myApiKey');

const msg = {
          to: email,
          from: {
            email: 'email',
            name: 'name'
          },
          templateId: 'd-85b61ed....',
          dynamic_template_data: {
            emailVerificationLink: 'a link',
          }
        };

        return sgMail.send(msg)

#### Technical details:

* "@sendgrid/mail": "^6.4.0",
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.2.0",
* Node.js Version: 6.9

**Comment by ajgomezrivera** [comment]
By switching from Node6 to Node8 in firebase function the error disappeared.
